

from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####
include: "rules/common.smk"

if config["use_scallop"]:
    include: "rules/scallop.smk"

if config["use_stringtie"]:
    include: "rules/stringtie.smk"

if config["use_mikado"]:
    include: "rules/mikado.smk"

##### target rules #####

if config["use_scallop"]:
    if config["use_stringtie"]:
        if config["use_mikado"]:

            rule all:
                input:
                    "results/annotation/combined.gtf"
        else:

            rule all:
                input:
                    directory("results/scallop_annotation/")
                    "results/stringtie_annotation/stringtie.gtf"
    else:
        rule all:
            input:
                directory("results/scallop_annotation/")
else:
    rule all:
        input:
            "results/stringtie_annotation/stringtie.gtf"