from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"



##### Check for potentially missing config parameters #####

if "long_reads" not in config:
    config["long_reads"] = []

if "stringtie_longread_params" not in config:
    config["stringtie_longread_params"] = ""

if "stringtie_merge_longread_params" not in config:
    config["stringtie_merge_longread_params"] = ""


##### load rules #####

include: "rules/common.smk"
include: "rules/stringtie.smk"
include: "rules/clean_assemblies.smk"
include: "rules/clean_ref.smk"
include: "rules/score.smk"
include: "rules/longread_assembly.smk"

##### target rules #####


rule all:
    input:
        get_target_input(),
