##### PARAMETERS TO ALTER

# Path to bam files, relative to directory that AnnotationCleaner was deployed to
samples:
  Rep_1: data/bam/WT_replicate_1.bam
  Rep_2: data/bam/WT_replicate_2.bam
  Rep_3: data/bam/WT_replicate_3.bam


##### PARAMETERS THAT DETERMINE WHICH TRANSCRIPTOME ASSEMBLERS TO USE

# Use Scallop + TACO for annotation building
scallop: 
  use_scallop: True
  label: "sc"
  strandedness: True
  score: 0
  is_reference: False
  exclude_redundant: False
  strip_cds: False

# Use StringTie for annotation building
stringtie: 
  use_stringtie: True
  label: "st"
  strandedness: True
  score: 0
  is_reference: False
  exclude_redundant: False
  strip_cds: False

# Use mikado to combine annotations built by multiple tools
use_mikado: True


##### PARAMETERS AFFECTING ALL ASSEMBLERS

# Parameters to pass to samtools (other than input, output, -m, and -T)
samtools_params: ""


##### SCALLOP PARAMETERS

# Parameters to pass to scallop (other than input and output)
scallop_params: ""

# Parameters to pass to TACO with Scallop input (other than input, output, and threads)
scallop_taco_params: ""

# Parameters to pass to TACO refcomp with Scallop input (other than output, reference, and test annotation)
scallop_refcomp_params: ""


##### STRINGTIE PARAMETERS


# Parameters to pass to Stringtie 
stringtie_params: ""

# Parameters to psas to Stringtie --merge
stringtie_merge_params: ""

# Parameters to pass to TACO with Stringtie input
stringtie_taco_params: ""

# Parameters to pass to TACO refcomp with Stringtie input (other than output, reference, and test annotation)
stringtie_refcomp_params: ""


##### MIKADO PARAMETERS

# Annotation GTF to compare assemblies to 
reference_gtf: 
  rf: # Label to give to reference for mikado
    annotation: data/annotation/reference.gtf # path to reference
    strandedness: True # strandedness of reference
    score: 0 # Score assigned to reference
    is_reference: True # treat this like a reference
    exclude_redundant: False # exclude redundant gene models
    strip_cds: False # Skip the chimera split routine


# Annotations you are bringing in
provided_annotations:
  sq: # Label
    annotation: path/to/squanti_annotation # Path to annotation
    strandedness: True # Strandedness
    score: 0 # Score for Mikado
    is_reference: False # Treat this as a reference?
    exclude_redundant: False #
    strip_cds: False
  cl: 
    annotation: path/to/CLASS2_annotation
    strandedness: True
    score: 0
    is_reference: False
    exclude_redundant: False
    strip_cds: False


# Reference genome fasta
genome: data/genome/reference.fasta

# Reference proteome fasta
proteome: data/proteome/reference.fasta

portcullis_prep_params: ""
portcullis_junc_params: ""
portcullis_strandedness: "firststrand"
portcullis_orientation: "RF"

mikado_configure_params: ""

mikado_prepare_params: ""

orf_min_length: 100
transdecoder_params: ""

mikado_serialise_params: ""

mikado_pick_params: ""
