##### PARAMETERS TO ALTER

# Path to bam files, relative to directory that AnnotationCleaner was deployed to
samples:
  Rep_1: data/bam/WT_replicate_1.bam
  Rep_2: data/bam/WT_replicate_2.bam
  Rep_3: data/bam/WT_replicate_3.bam


##### PARAMETERS THAT DETERMINE WHICH TRANSCRIPTOME ASSEMBLERS TO USE

# Use Scallop + TACO for annotation building
scallop: 
  use_scallop: True
  use_taco: True
  label: "sc"
  strandedness: True
  score: 0
  is_reference: False
  exclude_redundant: False
  strip_cds: False

# Use StringTie for annotation building
stringtie: 
  use_stringtie: True
  use_taco: True
  use_merge: False
  label: "st"
  strandedness: True
  score: 0
  is_reference: False
  exclude_redundant: False
  strip_cds: False

# Use mikado to combine annotations built by multiple tools
use_mikado: True


##### PARAMETERS AFFECTING ALL ASSEMBLERS

# Annotation GTF to compare assemblies to
reference_gtf: data/annotation/reference.gtf


# Parameters to pass to samtools (other than input, output, -m, and -T)
samtools_params: ""


##### SCALLOP PARAMETERS

# Parameters to pass to scallop (other than input and output)
scallop_params: "--library_type first"

# Parameters to pass to TACO with Scallop input (other than input, output, and threads)
scallop_taco_params: "--gtf-expr-attr RPKM"

# Parameters to pass to TACO refcomp with Scallop input (other than output, reference, and test annotation)
scallop_refcomp_params: ""


##### STRINGTIE PARAMETERS


# Parameters to pass to Stringtie 
stringtie_params: "--rf"

# Parameters to psas to Stringtie --merge
stringtie_merge_params: ""

# Parameters to pass to TACO with Stringtie input
stringtie_taco_params: ""

# Parameters to pass to TACO refcomp with Stringtie input (other than output, reference, and test annotation)
stringtie_refcomp_params: ""


##### MIKADO PARAMETERS

# Path to mikado list input (must have .txt extension)
  # This is created automatically if not already provided
mikado_list: data/mikado/mikado_list.txt

# Path to scoring function yaml file
mikado_scoring: data/mikado/scoring.yaml

# Reference genome fasta
genome: data/genome/reference.fasta

# Database to BLAST
blast_db: data/blast_db/reference.fasta


# Annotations you are bringing in
provided_annotations:
  sq: # Label
    annotation: path/to/squanti_annotation # Path to annotation
    strandedness: True # Strandedness
    score: 0 # Score for Mikado
    is_reference: False # Treat this as a reference?
    exclude_redundant: False #
    strip_cds: False
  cl: 
    annotation: path/to/CLASS2_annotation
    strandedness: True
    score: 0
    is_reference: False
    exclude_redundant: False
    strip_cds: False
  rf: # Label to give to reference for mikado
    annotation: data/annotation/reference.gtf # path to reference
    strandedness: True # strandedness of reference
    score: 0 # Score assigned to reference
    is_reference: False # treat this like a reference (False means don't always keep reference transcripts)
    exclude_redundant: False # exclude redundant gene models
    strip_cds: False # Skip the chimera split routine


## Required portcullis parameters
portcullis_strandedness: "firststrand"
portcullis_orientation: "RF"


## Optional portcullis parameters
portcullis_prep_params: ""
portcullis_junc_params: ""


## Optional TransDecoder parameters
transdecoder_params: ""

## Optional blastx parameters
blastx_params: "-max_target_seqs 5"

## Optional mikado pipeline parameters
mikado_configure_params: ""
mikado_prepare_params: ""
mikado_serialise_params: ""
mikado_pick_params: ""
