name: Tests

on:
  push:
    branches:
      - main
      - featurecount
      - develop
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Formatting
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: featurecount
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
        
  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - formatting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test assembly
      uses: ezherman/snakemake-github-action@5027c0eb6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test clean only
      uses: ezherman/snakemake-github-action@5027c0eb6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_clean.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"